const uuidv4 = require('uuid/v4');

module.exports = {
    obj_id : uuidv4(),
    obj_year : 2017,
    user_id : 'mynaman85@gmail.com',
    target : '목 표',
    idea1 : '프로그래밍',
    idea2 : '운동',
    idea3 : '책읽기',
    idea4 : '멘탈',
    idea5 : '자동차',
    idea6 : '습관',
    idea7 : '요리',
    idea8 : '도전과제',

    plan1_1 : 'express',
    plan1_2 : 'javascript', 
    plan1_3 : 'react',
    plan1_4 : 'nodejs',
    plan1_5 : 'c++',
    plan1_6 : 'c#',
    plan1_7 : 'angular',
    plan1_8 : 'vue',

    plan2_1 : '자전거',
    plan2_2 : '헬스',
    plan2_3 : '축구',
    plan2_4 : '농구',
    plan2_5 : '배구',
    plan2_6 : '야구',
    plan2_7 : '수영',
    plan2_8 : '레이싱',

    plan3_1 : '언어의온도',
    plan3_2 : '완득이',
    plan3_3 : '열정과냉정사이',
    plan3_4 : '7년의밤',
    plan3_5 : 'nodejs교과서',
    plan3_6 : '프로그래머의 멘토',
    plan3_7 : '행복한 개발자',
    plan3_8 : '개발자의 삶',

    plan4_1 : 'express',
    plan4_2 : 'javascript',
    plan4_3 : 'react',
    plan4_4 : 'nodejs',
    plan4_5 : 'c++',
    plan4_6 : 'c#',
    plan4_7 : 'angular',
    plan4_8 : 'vue',

    plan5_1 : 'express',
    plan5_2 : 'javascript',
    plan5_3 : 'react',
    plan5_4 : 'nodejs',
    plan5_5 : 'c++',
    plan5_6 : 'c#',
    plan5_7 : 'angular',
    plan5_8 : 'vue',

    plan6_1 : 'express',
    plan6_2 : 'javascript',
    plan6_3 : 'react',
    plan6_4 : 'nodejs',
    plan6_5 : 'c++',
    plan6_6 : 'c#',
    plan6_7 : 'angular',
    plan6_8 : 'vue',

    plan7_1 : 'express',
    plan7_2 : 'javascript',
    plan7_3 : 'react',
    plan7_4 : 'nodejs',
    plan7_5 : 'c++',
    plan7_6 : 'c#',
    plan7_7 : 'angular',
    plan7_8 : 'vue',
    
    plan8_1 : 'express',
    plan8_2 : 'javascript',
    plan8_3 : 'react',
    plan8_4 : 'nodejs',
    plan8_5 : 'c++',
    plan8_6 : 'c#',
    plan8_7 : 'angular',
    plan8_8 : 'vue',
    
    create_dt : Date.now(),
}