const uuidv4 = require('uuid/v4');

module.exports = {
    obj_id : uuidv4(),
    obj_year : 2017,
    user_id : 'mynaman85@gmail.com',
    target : '이직',
    idea1 : '프로그래밍',
    idea2 : '운동',
    idea3 : '책읽기',
    idea4 : '결혼',
    idea5 : '자동차',
    idea6 : '습관',
    idea7 : '요리',
    idea8 : '도전과제',

    paln1_1 : 'express',
    paln1_2 : 'javascript', 
    paln1_3 : 'react',
    paln1_4 : 'nodejs',
    paln1_5 : 'c++',
    paln1_6 : 'c#',
    paln1_7 : 'angular',
    paln1_8 : 'vue',

    paln2_1 : 'express',
    paln2_2 : 'javascript',
    paln2_3 : 'react',
    paln2_4 : 'nodejs',
    paln2_5 : 'c++',
    paln2_6 : 'c#',
    paln2_7 : 'angular',
    paln2_8 : 'vue',

    paln3_1 : 'express',
    paln3_2 : 'javascript',
    paln3_3 : 'react',
    paln3_4 : 'nodejs',
    paln3_5 : 'c++',
    paln3_6 : 'c#',
    paln3_7 : 'angular',
    paln3_8 : 'vue',

    paln4_1 : 'express',
    paln4_2 : 'javascript',
    paln4_3 : 'react',
    paln4_4 : 'nodejs',
    paln4_5 : 'c++',
    paln4_6 : 'c#',
    paln4_7 : 'angular',
    paln4_8 : 'vue',

    paln5_1 : 'express',
    paln5_2 : 'javascript',
    paln5_3 : 'react',
    paln5_4 : 'nodejs',
    paln5_5 : 'c++',
    paln5_6 : 'c#',
    paln5_7 : 'angular',
    paln5_8 : 'vue',

    paln6_1 : 'express',
    paln6_2 : 'javascript',
    paln6_3 : 'react',
    paln6_4 : 'nodejs',
    paln6_5 : 'c++',
    paln6_6 : 'c#',
    paln6_7 : 'angular',
    paln6_8 : 'vue',

    paln7_1 : 'express',
    paln7_2 : 'javascript',
    paln7_3 : 'react',
    paln7_4 : 'nodejs',
    paln7_5 : 'c++',
    paln7_6 : 'c#',
    paln7_7 : 'angular',
    paln7_8 : 'vue',
    
    paln8_1 : 'express',
    paln8_2 : 'javascript',
    paln8_3 : 'react',
    paln8_4 : 'nodejs',
    paln8_5 : 'c++',
    paln8_6 : 'c#',
    paln8_7 : 'angular',
    paln8_8 : 'vue',
    
    create_dt : Date.now(),
}