const uuidv4 = require('uuid/v4');



const objective = {        
    create(req) {        
        return {
            obj_id : uuidv4(),
            obj_year : (new Date()).getFullYear(),
            user_id : req.user.email,
            target : req.body.target,
            idea1 : req.body.idea1[0],
            idea2 : req.body.idea2[0],
            idea3 : req.body.idea3[0],
            idea4 : req.body.idea4[0],
            idea5 : req.body.idea5[0],
            idea6 : req.body.idea6[0],
            idea7 : req.body.idea7[0],
            idea8 : req.body.idea8[0],

            plan1_1 : req.body.plan1_1,
            plan1_2 : req.body.plan1_2,
            plan1_3 : req.body.plan1_3,
            plan1_4 : req.body.plan1_4,
            plan1_5 : req.body.plan1_5,
            plan1_6 : req.body.plan1_6,
            plan1_7 : req.body.plan1_7,
            plan1_8 : req.body.plan1_8,

            plan2_1 : req.body.plan2_1,
            plan2_2 : req.body.plan2_2,
            plan2_3 : req.body.plan2_3,
            plan2_4 : req.body.plan2_4,
            plan2_5 : req.body.plan2_5,
            plan2_6 : req.body.plan2_6,
            plan2_7 : req.body.plan2_7,
            plan2_8 : req.body.plan2_8,

            plan3_1 : req.body.plan3_1,
            plan3_2 : req.body.plan3_2,
            plan3_3 : req.body.plan3_3,
            plan3_4 : req.body.plan3_4,
            plan3_5 : req.body.plan3_5,
            plan3_6 : req.body.plan3_6,
            plan3_7 : req.body.plan3_7,
            plan3_8 : req.body.plan3_8,

            plan4_1 : req.body.plan4_1,
            plan4_2 : req.body.plan4_2,
            plan4_3 : req.body.plan4_3,
            plan4_4 : req.body.plan4_4,
            plan4_5 : req.body.plan4_5,
            plan4_6 : req.body.plan4_6,
            plan4_7 : req.body.plan4_7,
            plan4_8 : req.body.plan4_8,

            plan5_1 : req.body.plan5_1,
            plan5_2 : req.body.plan5_2,
            plan5_3 : req.body.plan5_3,
            plan5_4 : req.body.plan5_4,
            plan5_5 : req.body.plan5_5,
            plan5_6 : req.body.plan5_6,
            plan5_7 : req.body.plan5_7,
            plan5_8 : req.body.plan5_8,

            plan6_1 : req.body.plan6_1,
            plan6_2 : req.body.plan6_2,
            plan6_3 : req.body.plan6_3,
            plan6_4 : req.body.plan6_4,
            plan6_5 : req.body.plan6_5,
            plan6_6 : req.body.plan6_6,
            plan6_7 : req.body.plan6_7,
            plan6_8 : req.body.plan6_8,

            plan7_1 : req.body.plan7_1,
            plan7_2 : req.body.plan7_2,
            plan7_3 : req.body.plan7_3,
            plan7_4 : req.body.plan7_4,
            plan7_5 : req.body.plan7_5,
            plan7_6 : req.body.plan7_6,
            plan7_7 : req.body.plan7_7,
            plan7_8 : req.body.plan7_8,
            
            plan8_1 : req.body.plan8_1,
            plan8_2 : req.body.plan8_2,
            plan8_3 : req.body.plan8_3,
            plan8_4 : req.body.plan8_4,
            plan8_5 : req.body.plan8_5,
            plan8_6 : req.body.plan8_6,
            plan8_7 : req.body.plan8_7,
            plan8_8 : req.body.plan8_8,
            
            create_dt : Date.now(),
        }
    },

    modify(req) {        
        return {            
            target : req.body.target,
            idea1 : req.body.idea1[0],
            idea2 : req.body.idea2[0],
            idea3 : req.body.idea3[0],
            idea4 : req.body.idea4[0],
            idea5 : req.body.idea5[0],
            idea6 : req.body.idea6[0],
            idea7 : req.body.idea7[0],
            idea8 : req.body.idea8[0],

            plan1_1 : req.body.plan1_1,
            plan1_2 : req.body.plan1_2,
            plan1_3 : req.body.plan1_3,
            plan1_4 : req.body.plan1_4,
            plan1_5 : req.body.plan1_5,
            plan1_6 : req.body.plan1_6,
            plan1_7 : req.body.plan1_7,
            plan1_8 : req.body.plan1_8,

            plan2_1 : req.body.plan2_1,
            plan2_2 : req.body.plan2_2,
            plan2_3 : req.body.plan2_3,
            plan2_4 : req.body.plan2_4,
            plan2_5 : req.body.plan2_5,
            plan2_6 : req.body.plan2_6,
            plan2_7 : req.body.plan2_7,
            plan2_8 : req.body.plan2_8,

            plan3_1 : req.body.plan3_1,
            plan3_2 : req.body.plan3_2,
            plan3_3 : req.body.plan3_3,
            plan3_4 : req.body.plan3_4,
            plan3_5 : req.body.plan3_5,
            plan3_6 : req.body.plan3_6,
            plan3_7 : req.body.plan3_7,
            plan3_8 : req.body.plan3_8,

            plan4_1 : req.body.plan4_1,
            plan4_2 : req.body.plan4_2,
            plan4_3 : req.body.plan4_3,
            plan4_4 : req.body.plan4_4,
            plan4_5 : req.body.plan4_5,
            plan4_6 : req.body.plan4_6,
            plan4_7 : req.body.plan4_7,
            plan4_8 : req.body.plan4_8,

            plan5_1 : req.body.plan5_1,
            plan5_2 : req.body.plan5_2,
            plan5_3 : req.body.plan5_3,
            plan5_4 : req.body.plan5_4,
            plan5_5 : req.body.plan5_5,
            plan5_6 : req.body.plan5_6,
            plan5_7 : req.body.plan5_7,
            plan5_8 : req.body.plan5_8,

            plan6_1 : req.body.plan6_1,
            plan6_2 : req.body.plan6_2,
            plan6_3 : req.body.plan6_3,
            plan6_4 : req.body.plan6_4,
            plan6_5 : req.body.plan6_5,
            plan6_6 : req.body.plan6_6,
            plan6_7 : req.body.plan6_7,
            plan6_8 : req.body.plan6_8,

            plan7_1 : req.body.plan7_1,
            plan7_2 : req.body.plan7_2,
            plan7_3 : req.body.plan7_3,
            plan7_4 : req.body.plan7_4,
            plan7_5 : req.body.plan7_5,
            plan7_6 : req.body.plan7_6,
            plan7_7 : req.body.plan7_7,
            plan7_8 : req.body.plan7_8,
            
            plan8_1 : req.body.plan8_1,
            plan8_2 : req.body.plan8_2,
            plan8_3 : req.body.plan8_3,
            plan8_4 : req.body.plan8_4,
            plan8_5 : req.body.plan8_5,
            plan8_6 : req.body.plan8_6,
            plan8_7 : req.body.plan8_7,
            plan8_8 : req.body.plan8_8,
            
            modify_dt : Date.now(),
        }
    }
}

module.exports = objective;
