module.exports = (sequelize, DataTypes) => (
    sequelize.define('objective', {
        seq : {type : DataTypes.INTEGER, autoIncrement : true, unique: true},
        obj_id :{type : DataTypes.STRING(50), primaryKey : true},
        obj_year :{type: DataTypes.INTEGER(4).ZEROFILL, allowNull : false},
        user_id : {type: DataTypes.STRING(20), allowNull : false},

        target :{type : DataTypes.STRING(20), allowNull : true},
        idea1 :{type : DataTypes.STRING(20), allowNull : true},
        idea2 :{type : DataTypes.STRING(20), allowNull : true},
        idea3 :{type : DataTypes.STRING(20), allowNull : true},
        idea4 :{type : DataTypes.STRING(20), allowNull : true},
        idea5 :{type : DataTypes.STRING(20), allowNull : true},
        idea6 :{type : DataTypes.STRING(20), allowNull : true},
        idea7 :{type : DataTypes.STRING(20), allowNull : true},
        idea8 :{type : DataTypes.STRING(20), allowNull : true},

        plan1_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan1_8 :{type : DataTypes.STRING(20), allowNull : true},
        
        plan2_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan2_8 :{type : DataTypes.STRING(20), allowNull : true},

        plan3_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan3_8 :{type : DataTypes.STRING(20), allowNull : true},

        plan4_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan4_8 :{type : DataTypes.STRING(20), allowNull : true},

        plan5_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan5_8 :{type : DataTypes.STRING(20), allowNull : true},

        plan6_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan6_8 :{type : DataTypes.STRING(20), allowNull : true},

        plan7_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan7_8 :{type : DataTypes.STRING(20), allowNull : true},

        plan8_1 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_2 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_3 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_4 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_5 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_6 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_7 :{type : DataTypes.STRING(20), allowNull : true},
        plan8_8 :{type : DataTypes.STRING(20), allowNull : true},

        create_dt:{type: DataTypes.DATE, allowNull: true, defaultValue : null},
        modify_dt:{type: DataTypes.DATE, allowNull: true, defaultValue : null},
        delete_dt:{type: DataTypes.DATE, allowNull: true, defaultValue : null},
    },{
        timestamps : false,
        paranoid : false,
    })
);