module.exports = (sequelize, DataTypes) => (
    sequelize.define('objective', {
        seq : {type : DataTypes.INTEGER, autoIncrement : true, unique: true},
        obj_id :{type : DataTypes.STRING(50), primaryKey : true},
        obj_year :{type: DataTypes.INTEGER(4).ZEROFILL, allowNull : false},
        user_id : {type: DataTypes.STRING(20), allowNull : false},

        target :{type : DataTypes.STRING(20), allowNull : true},
        idea1 :{type : DataTypes.STRING(20), allowNull : true},
        idea2 :{type : DataTypes.STRING(20), allowNull : true},
        idea3 :{type : DataTypes.STRING(20), allowNull : true},
        idea4 :{type : DataTypes.STRING(20), allowNull : true},
        idea5 :{type : DataTypes.STRING(20), allowNull : true},
        idea6 :{type : DataTypes.STRING(20), allowNull : true},
        idea7 :{type : DataTypes.STRING(20), allowNull : true},
        idea8 :{type : DataTypes.STRING(20), allowNull : true},

        paln1_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln1_8 :{type : DataTypes.STRING(20), allowNull : true},
        
        paln2_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln2_8 :{type : DataTypes.STRING(20), allowNull : true},

        paln3_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln3_8 :{type : DataTypes.STRING(20), allowNull : true},

        paln4_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln4_8 :{type : DataTypes.STRING(20), allowNull : true},

        paln5_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln5_8 :{type : DataTypes.STRING(20), allowNull : true},

        paln6_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln6_8 :{type : DataTypes.STRING(20), allowNull : true},

        paln7_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln7_8 :{type : DataTypes.STRING(20), allowNull : true},

        paln8_1 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_2 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_3 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_4 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_5 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_6 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_7 :{type : DataTypes.STRING(20), allowNull : true},
        paln8_8 :{type : DataTypes.STRING(20), allowNull : true},

        create_dt:{type: DataTypes.DATE, allowNull: true, defaultValue : null},
        modify_dt:{type: DataTypes.DATE, allowNull: true, defaultValue : null},
        delete_dt:{type: DataTypes.DATE, allowNull: true, defaultValue : null},
    },{
        timestamps : false,
        paranoid : false,
    })
);